name: "Update Pull Request Body"

on: 
  workflow_dispatch:
    inputs:
      pull-request:
        description: overide pull request number
        required: true
        type: string

jobs:
  get-mci-vars:
    name: Get variables from mci-variables
    runs-on: ubuntu-latest
    outputs:
      start_time: ${{ steps.automation.outputs.start_time }}
    steps:
      - id: automation
        shell: bash
        run: |
          echo "start_time=$(date)" >> $GITHUB_OUTPUT
          
  update_pr:
    needs: get-mci-vars
    runs-on: ubuntu-latest
    outputs:
      headMatch: ${{ steps.update_pr.outputs.headMatch }}
      bodyUpdated: ${{ steps.update_pr.outputs.bodyUpdated }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - id: update_pr
        uses: rjmcnamara/pr-update-action@context-parameters
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pull-request: ${{ inputs.pull-request }}
          base-branch-regex: '.*'
          body-template: |
            - `Time Started: ${{ needs.get-mci-vars.outputs.start_time }}`
          body-update-action: 'suffix'
          
  update_pr_outputs:
    runs-on: ubuntu-latest
    needs: update_pr
    steps:
      - run: |
          echo 'bodyUpdated:' ${{needs.update_pr.outputs.bodyUpdated}}
